FROM trampgeek/jobeinabox:latest

RUN apt-get update
RUN apt-get install -y
RUN apt-get install npm -y
RUN pip install matplotlib
RUN apt-get install npm
RUN mkdir /home/jobe00
RUN chmod a+rwx /home/jobe00